logdir: logs
seed: None
cuda: 0
n_workers: 10
prefetch_factor: 2
persistent_workers: False
eval_every: 1
save_every: 1  # how often to checkpoint (epoch frequency)
checkpointing: True
timestamp: ???
wandb_id: ???
resume_wandb: allow
data_root: ./data
